const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:8000/api';

export interface InventoryItem {
  id: string;
  name: string;
  description?: string;
  quantity: number;
  price_per_unit: number;
  total_value: number;
  received_at: string;
  expiry_date?: string;
  
  // NEW: Customer-facing fields
  image_path?: string;
  image_url?: string;  // Generated by backend
  is_active: boolean;
  sku?: string;
  category?: string;
  
  // Relationships
  supplier?: { id: string; name: string };
  brand?: { id: string; name: string };
  supplier_name?: string;
  brand_name?: string;
  created_by_name?: string;
  
  created_at: string;
  updated_at: string;
}

export interface InventoryFormData {
  name: string;
  description?: string;
  quantity: number;
  price_per_unit: number;
  received_at: string;
  expiry_date?: string;
  supplier?: string;
  brand?: string;
  
  // NEW: Add these fields
  image_path?: string;
  is_active?: boolean;
  sku?: string;
  category?: string;
}

export const inventoryApi = {
  // Create inventory item (with image support)
  async create(itemData: InventoryFormData): Promise<InventoryItem> {
    const res = await fetch(`${API_BASE}/inventory/create/`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${localStorage.getItem('access_token')}`,
      },
      body: JSON.stringify(itemData),
    });
    if (!res.ok) {
      const error = await res.json();
      throw new Error(error.detail || 'Failed to create inventory item');
    }
    return await res.json();
  },

  // List all inventory items
  async list(): Promise<InventoryItem[]> {
    const res = await fetch(`${API_BASE}/inventory/`, {
      headers: {
        'Authorization': `Bearer ${localStorage.getItem('access_token')}`,
      },
    });
    if (!res.ok) throw new Error('Failed to fetch inventory items');
    return await res.json();
  },

  // Get single inventory item
  async get(id: string): Promise<InventoryItem> {
    const res = await fetch(`${API_BASE}/inventory/${id}/`, {
      headers: {
        'Authorization': `Bearer ${localStorage.getItem('access_token')}`,
      },
    });
    if (!res.ok) throw new Error('Failed to fetch inventory item');
    return await res.json();
  },

  // Update inventory item
  async update(id: string, itemData: Partial<InventoryFormData>): Promise<InventoryItem> {
    const res = await fetch(`${API_BASE}/inventory/${id}/update/`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${localStorage.getItem('access_token')}`,
      },
      body: JSON.stringify(itemData),
    });
    if (!res.ok) throw new Error('Failed to update inventory item');
    return await res.json();
  },

  // Delete inventory item
  async delete(id: string): Promise<void> {
    const res = await fetch(`${API_BASE}/inventory/${id}/delete/`, {
      method: 'DELETE',
      headers: {
        'Authorization': `Bearer ${localStorage.getItem('access_token')}`,
      },
    });
    if (!res.ok) throw new Error('Failed to delete inventory item');
  },

  // NEW: Customer-facing endpoints (no auth required)
  async getCustomerProducts(): Promise<InventoryItem[]> {
    const res = await fetch(`${API_BASE}/inventory/customer/products/`);
    if (!res.ok) throw new Error('Failed to fetch products');
    return await res.json();
  },

  async getCustomerProduct(id: string): Promise<InventoryItem> {
    const res = await fetch(`${API_BASE}/inventory/customer/products/${id}/`);
    if (!res.ok) throw new Error('Failed to fetch product');
    return await res.json();
  },
};